### ISSUE TITLE
What are these values for? 

### ISSUE THREAD

**Issue by vinhk** [gustavoavellar/multi-uav-planning#4]
I am not sure what dimension these values are in. Can you explain how did you calculate these values?

`mapWidth = abs(deg2km(E-W)*1000);
mapHeight = abs(deg2km(N-S)*1000);

Rx = base(1)/size(A,2);
Ry = base(2)/size(A,1);`

**Comment by gustavoavellar** [comment]
mapWidth and MapHeight are variables storing the size from opposing borders of the map in horizontal and vertical. The function deg2km receives a difference of degrees in the surface of earth and returns the distance of this arc in kilometers. Since I wanted to work in meters, the result is multiplied by 1000.

Rx and Ry are the location of the base in proportion to the size of the image.

**Comment by vinhk** [comment]
I understand. Thank you.
