### ISSUE TITLE
How did you use the values obtain in meters to do actual flight?

### ISSUE THREAD

**Issue by vinhk** [gustavoavellar/multi-uav-planning#5]
I am not clear on how were you able to do actual test flight. The coordinates would be in latitude and longitude but the coordinates in simulation is in meters. Would you be able to explain how you achieve the actual flight? 

Thanks

**Comment by gustavoavellar** [comment]
Quoting my answer to your question in youtube: The main reason to use meters instead of degrees is because it is easier to calculate using meters. Also, it gives the user a better sense of distance between UAVs and GCS and size of coverage area. The output of the algorithm is a list with waypoint coordinates in meters for each UAV that will be employed in that mission. Each waypoint consists of relative distance in meters in X and Y cartesian coordinates from GCS. This list can be used with UAV autopilots, such as Micropilot or Ardupilot.

**Comment by vinhk** [comment]
Thanks you. That was very informative. As I did not know that.

**Comment by vinhk** [comment]
Is Mission Planner an option for GCS? What do you recommend to test out the waypoints file in meters?

**Comment by gustavoavellar** [comment]
You have to verify if Mission Planner has relative waypoint capability. In
this project I used Micropilot's GCS (https://www.micropilot.com/).

Em ter, 2 de out de 2018 às 13:30, Vinh K <notifications@github.com>
escreveu:

**Comment by vinhk** [comment]
great. I will check

**Comment by vinhk** [comment]
Last question. 

I have been searching and Mission Planner does not support relative waypoint capability. I do not think most softwares do beside Micropilot. Do you have any ideas how I may extend your code to convert output in meters to degrees?

**Comment by gustavoavellar** [comment]
You can use [km2deg](https://www.mathworks.com/help/map/ref/km2deg.html) matlab function. Convert each waypoint coordinate relative to GCS and sum the results with lat,long coordinates of the GCS.

**Comment by vinhk** [comment]
thanks. I will try that. I will surely reference your work as my thesis.

**Comment by gustavoavellar** [comment]
Glad to hear that! Thanks!
